### ISSUE TITLE
写真へのアクセス方法を科目セルのタップ以外にも用意する

### ISSUE THREAD

**Issue by ksfee684** [coins-project/HomeworkManager#37]
写真へのアクセス方法を、科目セルのタップ以外にも用意してほしい（現状だと、先に写真だけ取っておいてあとで科目を入力することができない）

**Comment by TakayukiABE** [comment]
思い出した、セルに表示される「入力した日付」をタップするとその日の写真が見られるようにして欲しいって話だったわ
