### ISSUE TITLE
一覧のTableView化したい

### ISSUE THREAD

**Issue by ksfee684** [coins-project/HomeworkManager#45]

**Comment by ksfee684** [comment]
@TakayukiABE TableViewってどうやって作るんですか？

**Comment by khmkazu921** [comment]
コードへのコメント？方法がわからないのですが、
 `let homework = homeworkDictionary[keys[indexPath.row]]![indexPath.row]`
の使い方が不安です。よろしくお願いしますm(__)m

**Comment by TakayukiABE** [comment]
締切日をkeyにして、辞書型のhomeworkDictionaryから課題を取り出しています。
もっと良さそうな実装があれば書き換えてしまっても良いと思います。

**Comment by khmkazu921** [comment]
多分ここで落ちてしまうんです。
原因とか思い当たりますか？

```
  func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell: CustomCell = tableView.dequeueReusableCellWithIdentifier("CustomCell", forIndexPath: indexPath) as! CustomCell

        let homework = homeworkDictionary[keys[indexPath.row]]![indexPath.row]

        cell.close.text = DateFormatter.stringFromDate(homework.closeAt)
        cell.reference.text = homework.reference
        cell.subject.text = homework.subject?.name
        cell.backgroundColor = UIColor.hexStr(homework.subject!.hexColor, alpha: 1)

        cell.setCell(homework)
        return cell
    }
```

**Comment by ksfee684** [comment]
@khmkazu921 ↑の内容で落ちるんだったら一緒にエラーログも貼ったほうがわかりやすいよ

**Comment by khmkazu921** [comment]
なるほど、これです。
辞書の使い方の問題だと思っています...
ここに赤い矢印が出て止まります
`let homework = homeworkDictionary[keys[indexPath.row]]![indexPath.row]`
インデックスがおかしいみたいです
`fatal error: Index out of range`

**Comment by TakayukiABE** [comment]
あー、勘違いしてたごめんなさい。
ちょっと実行して確認まではできてないんだけど、keys[indexPath.row]じゃなくてkeys[indexPath.section]だったりはしないよね？

**Comment by khmkazu921** [comment]
# 今の問題点
- CustomViewにLabelが表示されないこと
- Cellをタップしても写真が表示されないこと（実機でないので確認できない）
