### ISSUE TITLE
TableViewでソートの方法を変更できる

### ISSUE THREAD

**Issue by khmkazu921** [coins-project/HomeworkManager#83]
## 締切日ソートだけでなく入力日ソートもできるようにする

- 今は締切日ソートだけである
- ボタンを追加して入力日ソートが選択できるようにする

**Comment by TakayukiABE** [comment]
@coins-project/aid PageViewで、横にスライドすると隣の画面では入力日のソートになっている、みたいな意見をもらいました。しかし、右から左にスライドする動作はTableViewCellの削除と被っていますね。どうしましょう？

**Comment by TakayukiABE** [comment]
案が思い浮かばないと実装もやりづらいので、とりあえずNavigationBarのTitle部分に現在のソート状況を表示して、そこをタップするとソートが切り替わるようにしようかな
