### ISSUE TITLE
日付をカレンダーなどで入力したい

### ISSUE THREAD

**Issue by ghost** [coins-project/HomeworkManager#87]
# 日付をカレンダーなどで入力できるようにする
- PickerViewだとずれてしまうため
- しかし画面遷移が増えるとタップ数が増えてしまう

**Comment by khmkazu921** [comment]
まずは長押しを実装してからになると思います。

**Comment by TakayukiABE** [comment]
- カレンダーは便利だが、カレンダーを不自由なく使えるならばPickerViewも不自由なく使えるはずだ（逆も然り）
- カレンダーの実装にはコストが結構かかりそう

上記の理由によりこれは実装しないものとします
